# Render.com configuration for João Macarrão Backend
# Deploy: Connect your GitHub repo to Render and point to this file

services:
  - type: web
    name: joao-macarrao-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: joao-macarrao-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: joao-macarrao-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://joao-macarrao.vercel.app
      # Add more env vars as needed

databases:
  - name: joao-macarrao-db
    databaseName: joao_macarrao
    user: joao_macarrao
    plan: free

