# Generated by Django 5.2 on 2025-10-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Avaliação Média'),
        ),
        migrations.AddField(
            model_name='dish',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Avaliações'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('money', 'Dinheiro'), ('debit', 'Cartão de Débito'), ('credit', 'Cartão de Crédito'), ('pix', 'PIX'), ('online', 'Pagamento Online')], default='money', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
