# Generated by Django 5.2 on 2025-10-23 04:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_dish_average_rating_dish_reviews_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='De 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('is_approved', models.BooleanField(default=True, help_text='Avaliações podem ser moderadas antes de aparecer publicamente', verbose_name='Aprovado')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Quantas pessoas acharam esta avaliação útil', verbose_name='Útil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.dish', verbose_name='Prato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação de Prato',
                'verbose_name_plural': 'Avaliações de Pratos',
                'ordering': ['-created_at'],
                'unique_together': {('dish', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='reviews.dishreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marcação de Útil',
                'verbose_name_plural': 'Marcações de Útil',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
