# Generated by Django 5.2 on 2025-10-23 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_dish_average_rating_dish_reviews_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('cash', 'Dinheiro')], max_length=20, verbose_name='Método de Pagamento')),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('mercadopago', 'Mercado Pago'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='Provedor de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Completo'), ('failed', 'Falhou'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('transaction_id', models.CharField(blank=True, help_text='ID da transação no gateway de pagamento', max_length=255, null=True, verbose_name='ID da Transação')),
                ('payment_intent_id', models.CharField(blank=True, help_text='ID do Payment Intent (Stripe)', max_length=255, null=True, verbose_name='Payment Intent ID')),
                ('preference_id', models.CharField(blank=True, help_text='ID da preferência (Mercado Pago)', max_length=255, null=True, verbose_name='Preference ID')),
                ('pix_qr_code', models.TextField(blank=True, help_text='Código do QR Code PIX para pagamento', null=True, verbose_name='QR Code PIX')),
                ('pix_qr_code_url', models.URLField(blank=True, null=True, verbose_name='URL QR Code PIX')),
                ('pix_copy_paste', models.TextField(blank=True, null=True, verbose_name='PIX Copia e Cola')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais do pagamento', verbose_name='Metadados')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado em')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order', verbose_name='Pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Provedor')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Dados do Webhook')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Webhook de Pagamento',
                'verbose_name_plural': 'Webhooks de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
